### ISSUE TITLE
Feature: User can search for recipes

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/recipe-finder#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to search for recipes using various search criteria

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="631" alt="Screen Shot 2021-06-08 at 12 46 08 PM" src="https://user-images.githubusercontent.com/82540886/121247902-a02dd400-c857-11eb-9382-630ba2e4ee5c.png">
<img width="184" alt="Screen Shot 2021-06-08 at 12 46 17 PM" src="https://user-images.githubusercontent.com/82540886/121247912-a1f79780-c857-11eb-9427-f6a4a6bd5792.png">
<img width="792" alt="Screen Shot 2021-06-08 at 12 47 41 PM" src="https://user-images.githubusercontent.com/82540886/121248034-c8b5ce00-c857-11eb-92ff-0a0ccb90647e.png">
<img width="792" alt="Screen Shot 2021-06-08 at 12 47 46 PM" src="https://user-images.githubusercontent.com/82540886/121248306-25b18400-c858-11eb-906c-c2c58eed91ce.png">

<img width="794" alt="Screen Shot 2021-06-08 at 12 47 56 PM" src="https://user-images.githubusercontent.com/82540886/121248171-f569e580-c857-11eb-9dad-d2548fcc0372.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Write an HTML and CSS page to design the home page
- [x] Design a layout for both mobile and desktop views
- [x] Mobile view contains the nav bar in a toggle button
- [x] Update the HTML to include a view for the search form
- [x] Add a 'click' event handler onto the search buttons that will change the view from the home page to the search form
- [x] When the user submits the form, take the given search criteria and query the API for results
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
