### ISSUE TITLE
Feature: User can view more search results

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/recipe-finder#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view more search results

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the recipe-list view container to have a button at the bottom of the page.
- [x] The button is toggled to hidden if the number of search results is less than or equal to 20
- [x] When the user presses the button:
     - [x] Play the loading spinner on the button
     - [x] Get the next API queries and push those results into the data.searchRecipes array
     - [x] Update the loadData function so that if data.search.from is not 1:
          - [x] destroyChildren, updatePageHeader, and switchView do not get called
          - [x] generateRecipeList gets called, but only from index (data.search.from - 1)
          - [x] reset the Show More button
- **Clean Up**
  - [x] Remove all console logs and comments
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
