### ISSUE TITLE
Feature: User can add recipes to their daily list

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/recipe-finder#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add recipes to a daily list in order to keep track of their nutrition intake for the day.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the data model to contain an array for a list of daily recipes.
- [x] Update the DOM generating function to have an icon for adding/removing recipes from the daily list
- [x] When the user presses the icon, the icon should toggle the transparent class
- [x] When the user presses the icon, the given recipe should be added to the daily list if it is not already inside of it
- [x] If the given recipe is already inside the daily list, remove it instead
- **Clean Up**
  - [x] Remove all console logs and comments
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
