### ISSUE TITLE
Feature: User can view daily recipes

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/recipe-finder#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a list of their daily recipes which they can add by pressing on the daily icons attached to each recipe.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the view container to contain another view for a list of daily recipes
- [x] The daily recipes page should show a table of the nutritional facts of all recipes in the data.dailyRecipes array
- [x] Create a function that will generate a table DOM for the nutritional facts 
- [x] Display both the nutrition table for the daily recipes as well as the daily recipes themselves
- [x] Update the clickNavLink and handleContentLoad functions so that the daily recipe list is generated each time the page loads or the view switches to daily-recipes
- **Clean Up**
  - [x] Remove all console logs and comments.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
