### ISSUE TITLE
Refactor to ES6

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/recipe-finder#20]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Change all var variables to const/let
- [x] Use destructuring where applicable
- [x] Use arrow functions for callbacks if applicable
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
