### ISSUE TITLE
Feature: User can view a list of recipes

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/recipe-finder#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a list of searched recipes

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="306" alt="Screen Shot 2021-06-09 at 12 31 01 PM" src="https://user-images.githubusercontent.com/82540886/121417308-9c18b980-c91e-11eb-8591-07b32447aed2.png">
<img width="784" alt="Screen Shot 2021-06-09 at 12 31 10 PM" src="https://user-images.githubusercontent.com/82540886/121417316-9d49e680-c91e-11eb-998f-ea964a3e2e44.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the data model so that the data will be stored in between refreshes
- [x] Use the data stored in the data model to create a template for a page that lets the user view their searched entries
- [x] Update the view containers to contain another view for viewing searched recipes
- [x] Create a function that will generate a DOM for each recipe in the search results
- [x] Assign a data-entry attribute to each DOM that corresponds to its search index number
- [x] Update the HTML page by appending each generated recipe DOM to the search viewer page
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
