### ISSUE TITLE
Feature: User can view recipe details

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/recipe-finder#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to click on a recipe in a list of recipes and get more details

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="314" alt="Screen Shot 2021-06-10 at 10 11 19 AM" src="https://user-images.githubusercontent.com/82540886/121568144-371f9b00-c9d4-11eb-8cbb-73064ec3db43.png">
<img width="773" alt="Screen Shot 2021-06-10 at 10 11 53 AM" src="https://user-images.githubusercontent.com/82540886/121568186-4999d480-c9d4-11eb-8c94-a1d1b46476fb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the switchView function to also store the previous view in the data model
- [x] Create an event listener to listen for 'DOMContentLoaded' events and will restore the previous view before refreshing
- [x] Update the styling on the recipe containers so that the user's cursor will be a pointer on hover
- [x] Add an event listener to the recipe list view container so that when the user clicks on a recipe, more info will be revealed
- [x] use local data to create a HTML/CSS template for the recipe's additional info
- [x] Set the additional info to be collapsible on each recipe and toggle the reveal class name on click
- [x] Update the DOM Generating function to remove the data-index attribute if not necessary
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
