### ISSUE TITLE
Feature: User can favorite recipes

### ISSUE THREAD

**Issue by solomonjin** [solomonjin/recipe-finder#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add recipes to a favorites list by clicking on the heart icon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Favorited Recipe
<img width="391" alt="Screen Shot 2021-06-10 at 5 14 36 PM" src="https://user-images.githubusercontent.com/82540886/121612477-57208000-ca0f-11eb-962a-08bd18fd40d9.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the document event listener for clicks so that it will distinguish between the user clicking on the recipe container and the heart icon
- [x] When the user clicks on a heart icon, create a function that:
    - [x] Changes the current heart icon to a icon that indicates it has been added to the favorites
    - [x] Identifies which recipe the user favorited and add it to the data model if it has not already been added to the list (compare their URLs)
- **Clean Up**
  - [x] Remove all console logs and comments
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Check for bugs
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
